### ISSUE TITLE
API

### ISSUE THREAD

**Issue by hearsilent** [kuastw/kuas_general_education_search#1]
可以改戳校務通 API
https://github.com/John-Thunder/AP-API/tree/bus-fix

**Comment by whyayen** [comment]
現在那 api server 還在嗎？

**Comment by louisom** [comment]
@yanzijun server 還在，可以看這個 docs,
http://kuas-api.readthedocs.io/en/v2/

**Comment by whyayen** [comment]
@grapherd 原來有這個 document ...
OK，感恩，這兩天改寫
