### ISSUE TITLE
Bug: the subject didn't pass , but count it too.

### ISSUE THREAD

**Issue by whyayen** [kuastw/kuas_general_education_search#2]
你應該要歷年成績判斷有沒有 60 才對，目前是如果有沒及格一樣列入統計。

**Comment by hearsilent** [comment]
可以參考我以前亂寫的 Code xD
https://github.com/kuastw/KUAS-AP-Windows/blob/master/KUAS%20AP/AP_Frm.vb#L1562-L1755

**Comment by louisom** [comment]
@yanzijun  \發PR/\發PR/\發PR/

**Comment by whyayen** [comment]
發了，可是我真的不太會送 PR  QQQQQQQ
